package vg

WindowHandle :: distinct rawptr

OsEventKind :: enum {
    Window_Close,
    Window_Resize,
    Press,
    Release,
    Mouse_Move,
    Scroll,
}

OsModifier :: enum {
    Ctrl,
    Shift,
    Alt,
}

OsModifiers :: bit_set[OsModifier]

OsEvent :: struct {
    next:      ^OsEvent,
    kind:      OsEventKind,
    window:    WindowHandle,
    width:     int,
    height:    int,
    key:       OsKey,
    modifiers: OsModifiers,
    pos_x:     int,
    pos_y:     int,
    delta_x:   int,
    delta_y:   int,
}

OsEventList :: struct {
    first: ^OsEvent,
    last:  ^OsEvent,
}

os_poll_events :: proc() -> OsEventList {
    return _os_poll_events()
}

os_key_name :: proc(key: OsKey) -> string {
    return os_key_names[key]
}

OsKey :: enum {
    None,
    Mouse_Left,
    Mouse_Middle,
    Mouse_Right,
    Mouse_X1,
    Mouse_X2,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    Num_0,
    Num_1,
    Num_2,
    Num_3,
    Num_4,
    Num_5,
    Num_6,
    Num_7,
    Num_8,
    Num_9,
    Numpad_0,
    Numpad_1,
    Numpad_2,
    Numpad_3,
    Numpad_4,
    Numpad_5,
    Numpad_6,
    Numpad_7,
    Numpad_8,
    Numpad_9,
    Numpad_Add,
    Numpad_Subtract,
    Numpad_Multiply,
    Numpad_Divide,
    Numpad_Decimal,
    Numpad_Enter,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    Left_Shift,
    Right_Shift,
    Left_Ctrl,
    Right_Ctrl,
    Left_Alt,
    Right_Alt,
    Left_Super,
    Right_Super,
    Escape,
    Enter,
    Space,
    Tab,
    Backspace,
    Delete,
    Insert,
    Home,
    End,
    Page_Up,
    Page_Down,
    Left,
    Right,
    Up,
    Down,
    Caps_Lock,
    Num_Lock,
    Scroll_Lock,
    Pause,
    Print_Screen,
    Grave,
    Minus,
    Equal,
    Left_Bracket,
    Right_Bracket,
    Backslash,
    Semicolon,
    Apostrophe,
    Comma,
    Period,
    Slash,
    ISO_Backslash,
    Menu,
}

@(private="package")
os_key_names := [OsKey]string{
    .None = "None",
    .Mouse_Left = "Left Mouse",
    .Mouse_Middle = "Middle Mouse",
    .Mouse_Right = "Right Mouse",
    .Mouse_X1 = "Mouse X1",
    .Mouse_X2 = "Mouse X2",
    .A = "A",
    .B = "B",
    .C = "C",
    .D = "D",
    .E = "E",
    .F = "F",
    .G = "G",
    .H = "H",
    .I = "I",
    .J = "J",
    .K = "K",
    .L = "L",
    .M = "M",
    .N = "N",
    .O = "O",
    .P = "P",
    .Q = "Q",
    .R = "R",
    .S = "S",
    .T = "T",
    .U = "U",
    .V = "V",
    .W = "W",
    .X = "X",
    .Y = "Y",
    .Z = "Z",
    .Num_0 = "0",
    .Num_1 = "1",
    .Num_2 = "2",
    .Num_3 = "3",
    .Num_4 = "4",
    .Num_5 = "5",
    .Num_6 = "6",
    .Num_7 = "7",
    .Num_8 = "8",
    .Num_9 = "9",
    .Numpad_0 = "Numpad 0",
    .Numpad_1 = "Numpad 1",
    .Numpad_2 = "Numpad 2",
    .Numpad_3 = "Numpad 3",
    .Numpad_4 = "Numpad 4",
    .Numpad_5 = "Numpad 5",
    .Numpad_6 = "Numpad 6",
    .Numpad_7 = "Numpad 7",
    .Numpad_8 = "Numpad 8",
    .Numpad_9 = "Numpad 9",
    .Numpad_Add = "Numpad +",
    .Numpad_Subtract = "Numpad -",
    .Numpad_Multiply = "Numpad *",
    .Numpad_Divide = "Numpad /",
    .Numpad_Decimal = "Numpad .",
    .Numpad_Enter = "Numpad Enter",
    .F1 = "F1",
    .F2 = "F2",
    .F3 = "F3",
    .F4 = "F4",
    .F5 = "F5",
    .F6 = "F6",
    .F7 = "F7",
    .F8 = "F8",
    .F9 = "F9",
    .F10 = "F10",
    .F11 = "F11",
    .F12 = "F12",
    .F13 = "F13",
    .F14 = "F14",
    .F15 = "F15",
    .F16 = "F16",
    .F17 = "F17",
    .F18 = "F18",
    .F19 = "F19",
    .F20 = "F20",
    .F21 = "F21",
    .F22 = "F22",
    .F23 = "F23",
    .F24 = "F24",
    .Left_Shift = "Left Shift",
    .Right_Shift = "Right Shift",
    .Left_Ctrl = "Left Ctrl",
    .Right_Ctrl = "Right Ctrl",
    .Left_Alt = "Left Alt",
    .Right_Alt = "Right Alt",
    .Left_Super = "Left Super",
    .Right_Super = "Right Super",
    .Escape = "Escape",
    .Enter = "Enter",
    .Space = "Space",
    .Tab = "Tab",
    .Backspace = "Backspace",
    .Delete = "Delete",
    .Insert = "Insert",
    .Home = "Home",
    .End = "End",
    .Page_Up = "Page Up",
    .Page_Down = "Page Down",
    .Left = "Left",
    .Right = "Right",
    .Up = "Up",
    .Down = "Down",
    .Caps_Lock = "Caps Lock",
    .Num_Lock = "Num Lock",
    .Scroll_Lock = "Scroll Lock",
    .Pause = "Pause",
    .Print_Screen = "Print Screen",
    .Grave = "Grave",
    .Minus = "Minus",
    .Equal = "Equal",
    .Left_Bracket = "Left Bracket",
    .Right_Bracket = "Right Bracket",
    .Backslash = "Backslash",
    .Semicolon = "Semicolon",
    .Apostrophe = "Apostrophe",
    .Comma = "Comma",
    .Period = "Period",
    .Slash = "Slash",
    .ISO_Backslash = "ISO Backslash",
    .Menu = "Menu",
}